[package]
name = "storage"
version = "0.5.0"
authors = ["The Nydus Developers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.35"
arc-swap = "0.4.6"
libc = "0.2"
nix = "0.17.0"
vm-memory = ">=0.2.0"
governor = "0.3.1"
log = "0.4.8"
serde = { version = ">=1.0.27", features = ["serde_derive", "rc"] }
serde_json = ">=1.0.9"
serde_with = { version = "1.6.0", features = ["macros"] }
nydus-utils = { path = "../utils" }
futures = "0.3"
flate2 = { version = "1.0", features = ["miniz-sys"], default-features = false }
lz4-sys = "1.9.2"
bitflags = ">=1.1.0"
spmc = "0.3.0"
base64 = { version = ">=0.12.0", optional = true }
sha2 = { version = "0.9.1", optional = true }
sha-1 = { version = "0.9.1", optional = true }
hmac = { version = "0.8.1", optional = true }
url = { version = "2.1.1", optional = true }
httpdate = { version = "0.3.2", optional = true }
reqwest = { version = "0.10.4", features = ["blocking", "json"], optional = true }


fuse-rs = { git = "https://github.com/cloud-hypervisor/fuse-backend-rs.git", rev = "cfd2cca" }


[dev-dependencies]
vmm-sys-util = ">=0.3.1"

[features]
backend-localfs = ["sha2"]
backend-oss = ["base64", "httpdate", "reqwest", "sha-1", "sha2", "hmac", "url"]
backend-registry = ["reqwest", "sha2", "url"]
